[project]
name = "msml605"
version = "0.1.0"
description = "The final project for MSML 605."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "loguru>=0.7.3",
    "mlcroissant>=1.0.22",
    "numpy>=2.2.6",
]

[project.scripts]
ingest-lfw = "msml605.scripts:ingest_lfw"

[build-system]
requires = ["uv_build>=0.10.7,<0.11.0"]
build-backend = "uv_build"
